### ISSUE TITLE
Download / Abo being diversen Podcasts nicht möglich.

### ISSUE THREAD

**Issue by mrxoom1274** [holgerkrupp/PodcastClient#17]
Kann z.B die Podcasts

- Schleifenquadrat
- Audiodump
- Connected mit Vittici
- Dirty Minutes Left 

Nicht abonnieren. Es passiert einfach nichts.

**Comment by holgerkrupp** [comment]
Moin. Danke ist bekannt. Die ganze Suche & abonnieren sind grad mit heißer Nadel gestrickt und werden noch komplett umgebaut.

**Comment by holgerkrupp** [comment]
Jetzt besser?

**Comment by mrxoom1274** [comment]
Leider nein. Das gleiche Ergebnis ![image](https://github.com/holgerkrupp/PodcastClient/assets/70346648/a5f64942-2e08-48f7-80e6-0b5167ad063e)

**Comment by mrxoom1274** [comment]
Moin. Sehe keinen Button. Es passiert immer noch nichts ![image](https://github.com/holgerkrupp/PodcastClient/assets/70346648/a644ce69-eda8-4e86-b05a-d39dea52d635)

**Comment by mrxoom1274** [comment]
Jaaaaa. Jetzt. Super. Danke.

**Comment by holgerkrupp** [comment]
Super. Danke fürs mithelfen beim finden des Problems.
