### ISSUE TITLE
Irreführendes Feedback beim Abonnieren von passwortgeschützten Feeds

### ISSUE THREAD

**Issue by SalocinHB** [holgerkrupp/PodcastClient#18]
Beim manuellen Abonnieren mit `user:pass@host`-URL gibt‘s nur nen endlos-Spinner:
![image](https://github.com/holgerkrupp/PodcastClient/assets/4649546/c5eb2353-31ef-4e1e-a592-abfce6abf88d)

Per OPML kommt zumindest noch ein bisschen Feedback in Form eines 401er Statuscodes
![image](https://github.com/holgerkrupp/PodcastClient/assets/4649546/d5033317-6a4f-4f09-8f15-4989a355f10c)

Wenn ich nun aber die Liste meiner Abos kontrolliere scheint der Podcast doch abonniert worden zu sein.

**Comment by holgerkrupp** [comment]
Hmm bei mir hat es funktioniert. in meiner OPML Datei ist aber auch nach plus noch ein / - ggf hat das damit zu tun. muss ich mal checken.

**Comment by holgerkrupp** [comment]
Hab grad ne Version in TestFlight geschoben, die anzeigen sollte warum ein Feed nicht abonniert werden kann.

**Comment by holgerkrupp** [comment]
geht es jetzt mit der neuen Version?

**Comment by SalocinHB** [comment]
Ja, geht
